# version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: HIMANSHU
      POSTGRES_PASSWORD: him123456
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URL: postgresql://HIMANSHU:him123456@postgres:5432/school
    depends_on:
      - postgres

volumes:
  postgres_data:
